name: banking-api-dev

services:
  app:
    build: .
    container_name: banking-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - banking-network

  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    env_file:
      - .env
    volumes:
      - banking_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  banking_mysql_data:
